#!/bin/sh
# git_remote_branch <branch_name>

if [ $# -ne 1 ]; then
  echo 1>&2 Usage: $0 branch_name
  exit 127
fi

branch_name=$1
echo "Pushing . Creating ${branch_name}"
git push -u origin origin:refs/heads/$branch_name
echo "Fetching"
git fetch origin
echo "Branch"
git branch --set-upstream --track ${branch_name} origin/${branch_name}
echo "Checkout"
git checkout $branch_name

