#!/bin/bash
 
for branch in $(git branch -r); do
  if ([ "$branch" == "origin/HEAD" ] || [ "$branch" == "origin/master" ] || [ "$branch" == "->" ]); then
    continue
  fi
  printf "$(git log $branch -n1 --date=iso | grep -Eow '[0-9]+-[0-9]+-[0-9]+') $branch\n";
done | sort

